// Sentence database for all languages and difficulty levels
export const sentences = {
  en: {
    easy: [
      "The cat sat on the mat and looked at the bird outside the window.",
      "I like to eat pizza and drink orange juice after school every day.",
      "The sun is bright and the sky is blue on this beautiful morning.",
      "She went to the store to buy some milk and fresh bread for dinner.",
      "The dog ran fast in the park and played with the little red ball.",
      "My friend and I like to play games on the computer after lunch.",
      "The flowers in the garden are very pretty and smell so nice today.",
      "He reads a new book every week because he loves to learn new things.",
      "We went to the beach and built a big sand castle near the water.",
      "The baby laughed when she saw the funny clown at the birthday party.",
      "I wake up early every morning and go for a walk in the park nearby.",
      "The teacher gave us homework and told us to finish it by tomorrow.",
      "Birds fly south in the winter to find warm places to live and eat.",
      "My mother cooks the best food and I always help her in the kitchen.",
      "The train was late today so we had to wait at the station for an hour.",
      "The boy played soccer with his friends in the field after school.",
      "I saw a rainbow in the sky after the rain stopped this afternoon.",
      "She likes to draw pictures of animals and color them with bright crayons.",
      "We ate dinner together and talked about our day at the table.",
      "The little girl sang a happy song while walking to school in the morning.",
      "He cleaned his room and put all his toys back in the box.",
      "The fish swim in the clear water and move their tails very fast.",
      "I wear my jacket when it is cold and windy outside in the evening.",
      "They watched a movie and ate popcorn on the sofa at home.",
      "The farmer grows vegetables and sells them at the market every week.",
      "My brother rides his bike to school and comes back in the afternoon.",
      "The stars shine brightly in the sky when the night is very clear.",
      "We visited our grandparents and had a nice lunch together on Sunday.",
      "The child drew a big house with a garden and a tall tree.",
      "She opened the window to let fresh air come into the room.",
      "The boy helped his father wash the car on a sunny day.",
      "I packed my bag and got ready for school early in the morning.",
      "The dog barked loudly when it saw a stranger near the gate.",
      "We planted flowers in the yard and watered them every day.",
      "The teacher smiled and praised the students for their good work."
    ],
    medium: [
      "The quick brown fox jumps over the lazy dog while the farmer watches from the old wooden fence near the barn.",
      "Programming is the art of telling a computer what to do using a language that both humans and machines can understand.",
      "The weather forecast predicted heavy rain throughout the weekend, so we decided to postpone our camping trip until next month.",
      "Learning a new language requires dedication, practice, and patience, but the rewards of being bilingual are truly remarkable.",
      "The ancient library contained thousands of manuscripts that scholars from around the world traveled great distances to study.",
      "Technology has transformed the way we communicate, work, and entertain ourselves in ways that previous generations could never have imagined.",
      "The mountain trail was steep and challenging, but the breathtaking view from the summit made every difficult step completely worthwhile.",
      "Scientists discovered a new species of deep-sea fish that can produce its own light in the darkest parts of the ocean.",
      "The orchestra performed a magnificent symphony that captivated the audience and received a standing ovation lasting several minutes.",
      "Education is the most powerful weapon which you can use to change the world and create a better future for everyone.",
      "The restaurant on the corner serves the most delicious pasta dishes that remind me of my grandmother traditional Italian cooking.",
      "Artificial intelligence is rapidly evolving and has the potential to revolutionize healthcare, transportation, and many other important industries.",
      "The photographer captured a stunning sunset over the ocean, with vibrant shades of orange, pink, and purple filling the entire sky.",
      "Regular exercise and a balanced diet are essential components of maintaining good health and preventing chronic diseases throughout your lifetime.",
      "The old bookstore downtown has been serving the community for over fifty years and remains a beloved gathering place for readers.",
      "The small village by the river becomes lively during the annual festival, attracting visitors who come to enjoy music, food, and traditional dances.",
      "She spent the entire afternoon organizing her workspace so that she could focus better and improve her productivity in the coming weeks.",
      "The new policy aims to reduce pollution by encouraging people to use public transportation instead of relying on private vehicles.",
      "After reading several reviews online, we decided to try the newly opened café that everyone had been talking about recently.",
      "The documentary explores the history of space exploration and highlights the achievements of scientists and astronauts over the decades.",
      "He carefully saved his money for months in order to buy a laptop that would help him complete his school projects more efficiently.",
      "The team worked together to solve the complex problem, combining their knowledge and skills to find a practical solution.",
      "During the long journey, we listened to music, shared stories, and enjoyed the changing scenery outside the window.",
      "The company introduced a flexible work schedule to help employees maintain a better balance between their professional and personal lives.",
      "Researchers are studying climate change to understand its impact on ecosystems and to develop strategies for protecting the environment.",
      "She felt nervous before the presentation, but her confidence grew as she began to explain her ideas clearly to the audience.",
      "The city has invested in new infrastructure projects to improve transportation and support economic growth in the region.",
      "Reading books regularly can expand your knowledge, improve your vocabulary, and enhance your ability to think critically.",
      "The artist used a variety of colors and textures to create a unique painting that expresses deep emotions and personal experiences.",
      "Although the task seemed difficult at first, breaking it into smaller steps made it much easier to complete successfully.",
      "The museum exhibition features rare artifacts that provide insight into the culture and traditions of ancient civilizations.",
      "He decided to take an online course to develop new skills that would help him advance in his career.",
      "The garden looked beautiful in the spring, with flowers blooming and butterflies flying from one plant to another.",
      "The manager praised the team for their hard work and dedication in completing the project ahead of schedule.",
      "Traveling to different countries allows people to experience new cultures, taste different foods, and broaden their perspectives."
    ],
    hard: [
      "The unprecedented technological advancements of the twenty-first century have fundamentally restructured global communication networks, enabling instantaneous information exchange across continental boundaries and revolutionizing collaborative research methodologies.",
      "Quantum computing represents a paradigmatic shift in computational capabilities, leveraging the principles of superposition and entanglement to solve extraordinarily complex mathematical problems that would require conventional computers millennia to process.",
      "The philosophical implications of artificial general intelligence raise profound questions about consciousness, free will, and the fundamental nature of human cognition that have perplexed philosophers and neuroscientists for centuries.",
      "Biodiversity conservation requires a multifaceted approach encompassing habitat preservation, sustainable resource management, international cooperation, and comprehensive educational initiatives to address the accelerating rate of species extinction worldwide.",
      "The intricate relationship between socioeconomic factors and public health outcomes has been extensively documented through longitudinal epidemiological studies spanning multiple decades across diverse demographic populations.",
      "Contemporary architectural design increasingly incorporates biophilic principles, integrating natural elements and sustainable materials to create environments that simultaneously promote psychological well-being and minimize environmental impact.",
      "The geopolitical ramifications of climate change extend far beyond environmental degradation, encompassing resource scarcity, mass migration, economic instability, and the potential for unprecedented international conflicts over diminishing natural resources.",
      "Neuroplasticity research has demonstrated that the human brain maintains a remarkable capacity for structural and functional reorganization throughout the entire lifespan, challenging previously held assumptions about cognitive development.",
      "The democratization of information through digital platforms has simultaneously empowered marginalized communities and created unprecedented challenges related to misinformation, privacy, and the algorithmic amplification of extremist ideologies.",
      "Interdisciplinary collaboration between computational linguists, cognitive psychologists, and artificial intelligence researchers has yielded significant breakthroughs in natural language processing and machine translation technologies.",
      "The rapid proliferation of digital currencies has introduced complex regulatory challenges, compelling governments and financial institutions to reconsider traditional monetary policies and frameworks for economic stability.",
      "Advancements in genomic sequencing technologies have facilitated unprecedented insights into hereditary diseases, enabling the development of personalized medical treatments tailored to an individual's genetic profile.",
      "The ethical considerations surrounding data privacy have intensified as corporations increasingly collect, analyze, and monetize vast quantities of user-generated information across interconnected digital ecosystems.",
      "Global supply chain disruptions have highlighted the fragility of interconnected markets, prompting organizations to adopt more resilient and diversified logistical strategies.",
      "Theoretical physics continues to explore the possibility of multiple dimensions, proposing models that challenge conventional understandings of space, time, and the fundamental structure of the universe.",
      "Educational reform initiatives emphasize critical thinking and problem-solving skills, aiming to better prepare students for the complexities of an ever-evolving global economy.",
      "The integration of renewable energy sources into national power grids necessitates significant infrastructural adjustments and innovative storage solutions to ensure consistent energy distribution.",
      "Cultural globalization has led to the exchange and hybridization of traditions, languages, and artistic expressions, reshaping identities in both local and international contexts.",
      "The rise of remote work has transformed organizational dynamics, requiring new approaches to leadership, communication, and performance evaluation in distributed teams.",
      "Artificial neural networks, inspired by the structure of the human brain, have demonstrated remarkable capabilities in pattern recognition, predictive modeling, and decision-making processes.",
      "The preservation of endangered languages is critical for maintaining cultural diversity, as each language embodies unique worldviews, histories, and systems of knowledge.",
      "Space exploration initiatives have expanded beyond governmental agencies, with private companies playing an increasingly influential role in advancing aerospace technologies.",
      "Behavioral economics integrates insights from psychology and economics to better understand how individuals make decisions under conditions of uncertainty and limited information.",
      "Urbanization trends have created densely populated metropolitan areas, necessitating innovative solutions for housing, transportation, and sustainable resource management.",
      "The development of autonomous vehicles relies on complex sensor systems, machine learning algorithms, and real-time data processing to navigate dynamic environments safely.",
      "Philosophical debates regarding moral relativism challenge the notion of universal ethical standards, proposing that moral judgments are shaped by cultural and contextual factors.",
      "The acceleration of scientific discovery in the modern era is largely attributed to increased access to information, advanced computational tools, and global collaborative networks.",
      "Environmental policies must balance economic growth with ecological preservation, requiring nuanced strategies that address both immediate needs and long-term sustainability goals.",
      "The study of linguistics encompasses phonetics, syntax, semantics, and pragmatics, providing a comprehensive framework for analyzing the structure and use of language.",
      "Innovations in biotechnology have raised important ethical questions regarding genetic modification, cloning, and the potential consequences of altering living organisms."
    ]
  },
  id: {
    easy: [
      "Kucing itu duduk di atas tikar dan melihat burung di luar jendela dengan tenang.",
      "Saya suka makan nasi goreng dan minum teh manis setiap pagi sebelum berangkat.",
      "Matahari bersinar terang dan langit berwarna biru cerah di pagi hari ini.",
      "Ibu pergi ke pasar untuk membeli sayuran segar dan buah-buahan untuk makan malam.",
      "Anak-anak bermain di taman dengan gembira sambil berlari dan tertawa bersama teman.",
      "Ayah membaca koran setiap pagi sambil minum kopi hitam di teras rumah.",
      "Sekolah kami memiliki perpustakaan besar dengan banyak buku cerita yang menarik untuk dibaca.",
      "Hujan turun dengan deras sehingga kami tidak bisa bermain di luar rumah hari ini.",
      "Nenek memasak rendang yang sangat enak untuk acara makan bersama keluarga besar.",
      "Adik saya belajar membaca dan menulis di sekolah dasar dengan sangat rajin setiap hari.",
      "Kami pergi ke pantai dan bermain pasir sambil menikmati angin laut yang sejuk.",
      "Pohon mangga di halaman rumah sudah berbuah lebat dan siap untuk dipetik.",
      "Guru mengajarkan kami cara menghitung dan membaca dengan sabar di dalam kelas.",
      "Kakak membeli es krim rasa cokelat dan vanila untuk kami semua di sore hari.",
      "Burung-burung berkicau merdu di pagi hari membuat suasana menjadi sangat menyenangkan.",
      "Saya bangun pagi dan membantu ibu menyapu halaman rumah sebelum sarapan.",
      "Adik bermain dengan mainan baru yang dibelinya kemarin di toko dekat rumah.",
      "Kami belajar bersama di ruang tamu sambil mendengarkan musik yang pelan.",
      "Ayah memperbaiki sepeda yang rusak agar bisa digunakan kembali besok pagi.",
      "Ibu memasak sup hangat yang enak saat cuaca sedang dingin dan hujan.",
      "Teman saya datang ke rumah untuk bermain dan mengerjakan tugas bersama.",
      "Kami menonton televisi bersama keluarga setelah makan malam setiap hari.",
      "Kucing peliharaan kami tidur dengan nyenyak di atas sofa ruang keluarga.",
      "Saya membawa bekal dari rumah untuk dimakan saat istirahat di sekolah.",
      "Kami berjalan kaki ke taman sambil menikmati udara segar di sore hari.",
      "Adik menggambar rumah dan pohon dengan pensil warna di buku gambarnya.",
      "Ibu mencuci pakaian di pagi hari dan menjemurnya di halaman belakang.",
      "Ayah mengajak kami pergi jalan-jalan ke kebun binatang pada hari libur.",
      "Kami membeli buah segar di pasar untuk dimakan bersama keluarga di rumah.",
      "Burung kecil hinggap di dahan pohon dan bernyanyi dengan suara yang indah.",
      "Saya membaca buku cerita sebelum tidur agar bisa bermimpi dengan indah.",
      "Kami bermain bola di lapangan dekat rumah bersama teman-teman setiap sore.",
      "Ibu membuat kue manis yang harum dan lezat untuk kami nikmati bersama.",
      "Adik belajar mengikat tali sepatu dengan bantuan kakak di rumah.",
      "Kami membantu orang tua membersihkan rumah agar tetap rapi dan nyaman."
    ],
    medium: [
      "Indonesia adalah negara kepulauan terbesar di dunia yang memiliki lebih dari tujuh belas ribu pulau dengan keanekaragaman budaya yang sangat kaya.",
      "Pendidikan merupakan kunci utama untuk membangun masa depan bangsa yang lebih baik dan menciptakan generasi muda yang berkualitas tinggi.",
      "Teknologi informasi telah mengubah cara kita berkomunikasi, bekerja, dan belajar dalam kehidupan sehari-hari secara signifikan.",
      "Keindahan alam Indonesia mulai dari sabang sampai merauke menarik wisatawan dari berbagai penjuru dunia untuk datang berkunjung.",
      "Gotong royong merupakan nilai budaya Indonesia yang mengajarkan pentingnya kerja sama dan saling membantu dalam kehidupan bermasyarakat.",
      "Perkembangan ekonomi digital di Indonesia menunjukkan pertumbuhan yang sangat pesat dalam beberapa tahun terakhir berkat inovasi teknologi.",
      "Pelestarian lingkungan hidup menjadi tanggung jawab bersama untuk menjaga kelestarian alam demi generasi mendatang yang lebih baik.",
      "Keanekaragaman hayati Indonesia merupakan salah satu yang terkaya di dunia dengan ribuan spesies flora dan fauna yang unik.",
      "Olahraga teratur dan pola makan seimbang sangat penting untuk menjaga kesehatan tubuh dan pikiran sepanjang kehidupan kita.",
      "Seni dan budaya tradisional Indonesia harus dilestarikan agar tidak punah dan tetap menjadi identitas bangsa yang membanggakan.",
      "Perpustakaan nasional menyimpan jutaan koleksi buku dan manuskrip kuno yang menjadi sumber pengetahuan berharga bagi peneliti.",
      "Pembangunan infrastruktur di daerah terpencil sangat penting untuk meningkatkan kesejahteraan masyarakat dan pemerataan ekonomi nasional.",
      "Kreativitas dan inovasi menjadi modal utama dalam menghadapi persaingan global yang semakin ketat di era modern ini.",
      "Museum sejarah nasional menyimpan berbagai artefak penting yang menceritakan perjalanan panjang bangsa Indonesia dari masa ke masa.",
      "Pengembangan energi terbarukan menjadi prioritas utama pemerintah untuk mengurangi ketergantungan pada bahan bakar fosil yang semakin menipis.",
      "Kemajuan teknologi komunikasi memungkinkan masyarakat untuk terhubung dengan orang lain di berbagai belahan dunia secara cepat dan efisien.",
      "Program pendidikan berbasis digital mulai diterapkan untuk meningkatkan akses belajar bagi siswa di daerah terpencil.",
      "Pariwisata lokal terus dikembangkan untuk meningkatkan pendapatan daerah dan membuka lapangan pekerjaan baru bagi masyarakat.",
      "Kesadaran masyarakat terhadap pentingnya menjaga kebersihan lingkungan semakin meningkat dalam beberapa tahun terakhir.",
      "Penelitian ilmiah berperan penting dalam menemukan solusi terhadap berbagai permasalahan global seperti perubahan iklim dan krisis energi.",
      "Transportasi umum yang nyaman dan terjangkau dapat membantu mengurangi kemacetan di kota-kota besar.",
      "Peran generasi muda sangat penting dalam menjaga kelestarian budaya dan nilai-nilai tradisional bangsa.",
      "Pemerintah terus berupaya meningkatkan kualitas layanan kesehatan untuk memastikan kesejahteraan seluruh masyarakat.",
      "Kegiatan membaca secara rutin dapat meningkatkan wawasan dan kemampuan berpikir kritis seseorang.",
      "Kerja sama internasional diperlukan untuk menghadapi tantangan global yang tidak dapat diselesaikan oleh satu negara saja.",
      "Penggunaan media sosial harus dilakukan secara bijak agar tidak menimbulkan dampak negatif dalam kehidupan sehari-hari.",
      "Industri kreatif berkembang pesat dengan memanfaatkan teknologi digital untuk menghasilkan berbagai karya inovatif.",
      "Pelatihan keterampilan kerja sangat dibutuhkan untuk meningkatkan daya saing tenaga kerja di era globalisasi.",
      "Pengelolaan sumber daya alam yang berkelanjutan sangat penting untuk menjaga keseimbangan lingkungan.",
      "Perkembangan kota pintar atau smart city menjadi solusi untuk meningkatkan efisiensi pelayanan publik.",
      "Inovasi di bidang pertanian membantu meningkatkan hasil panen dan kesejahteraan para petani.",
      "Literasi digital menjadi kemampuan penting yang harus dimiliki oleh masyarakat di era teknologi saat ini.",
      "Kegiatan olahraga bersama dapat mempererat hubungan sosial antarwarga di lingkungan sekitar.",
      "Pengembangan usaha kecil dan menengah berkontribusi besar terhadap pertumbuhan ekonomi nasional.",
      "Pendidikan karakter di sekolah membantu membentuk kepribadian siswa yang bertanggung jawab dan berintegritas."
    ],
    hard: [
      "Transformasi digital yang berlangsung secara masif di berbagai sektor kehidupan telah menciptakan paradigma baru dalam tata kelola pemerintahan, sistem pendidikan, dan dinamika perekonomian nasional yang memerlukan adaptasi berkelanjutan dari seluruh elemen masyarakat.",
      "Implementasi kebijakan pembangunan berkelanjutan memerlukan sinergi antara pemerintah pusat, pemerintah daerah, sektor swasta, dan masyarakat sipil untuk mencapai keseimbangan antara pertumbuhan ekonomi, pelestarian lingkungan, dan keadilan sosial bagi seluruh rakyat Indonesia.",
      "Perkembangan ilmu pengetahuan dan teknologi yang sangat pesat menuntut reformasi menyeluruh dalam sistem pendidikan nasional agar mampu menghasilkan sumber daya manusia yang kompetitif, inovatif, dan adaptif terhadap perubahan zaman yang semakin dinamis.",
      "Kearifan lokal masyarakat adat Indonesia yang telah diwariskan secara turun-temurun selama berabad-abad mengandung nilai-nilai filosofis mendalam tentang harmonisasi hubungan antara manusia dengan alam semesta yang sangat relevan dengan konsep pembangunan berkelanjutan modern.",
      "Diplomasi multilateral Indonesia dalam forum internasional mencerminkan komitmen bangsa terhadap perdamaian dunia, kerja sama ekonomi regional, dan penyelesaian konflik secara damai berdasarkan prinsip-prinsip hukum internasional yang berkeadilan.",
      "Revolusi industri keempat membawa tantangan sekaligus peluang bagi Indonesia untuk melakukan lompatan pembangunan melalui pemanfaatan kecerdasan buatan, internet of things, dan teknologi blockchain dalam berbagai aspek kehidupan masyarakat.",
      "Pengelolaan sumber daya alam yang bertanggung jawab memerlukan pendekatan komprehensif yang mengintegrasikan aspek ekologi, ekonomi, dan sosial budaya untuk memastikan keberlanjutan pemanfaatannya bagi generasi sekarang dan yang akan datang.",
      "Ketahanan pangan nasional merupakan isu strategis yang memerlukan perhatian serius dari seluruh pemangku kepentingan mengingat pertumbuhan populasi yang terus meningkat dan perubahan iklim yang semakin mengancam produktivitas sektor pertanian.",
      "Pengembangan infrastruktur konektivitas digital di seluruh wilayah nusantara menjadi prasyarat fundamental bagi terciptanya pemerataan akses informasi dan kesempatan ekonomi yang berkeadilan bagi seluruh lapisan masyarakat Indonesia.",
      "Preservasi warisan budaya takbenda Indonesia yang telah diakui oleh UNESCO memerlukan strategi pelestarian yang komprehensif melibatkan dokumentasi sistematis, transmisi antargenerasi, dan revitalisasi dalam konteks kehidupan masyarakat kontemporer.",
      "Disrupsi teknologi dalam era digital telah mengubah lanskap industri secara fundamental, memaksa perusahaan untuk berinovasi secara berkelanjutan agar tetap relevan dan kompetitif di tengah persaingan global yang semakin intensif.",
      "Integrasi kecerdasan buatan dalam sistem pelayanan publik berpotensi meningkatkan efisiensi birokrasi, namun juga menimbulkan tantangan etis terkait transparansi, akuntabilitas, dan perlindungan data pribadi masyarakat.",
      "Pendekatan interdisipliner dalam penelitian ilmiah semakin diperlukan untuk menjawab permasalahan kompleks yang melibatkan berbagai dimensi, mulai dari aspek sosial, ekonomi, hingga lingkungan hidup.",
      "Urbanisasi yang tidak terkendali dapat menimbulkan berbagai permasalahan struktural seperti kepadatan penduduk, kemacetan lalu lintas, serta ketimpangan akses terhadap layanan dasar di wilayah perkotaan.",
      "Penguatan sistem hukum nasional menjadi fondasi penting dalam menciptakan kepastian hukum dan keadilan sosial bagi seluruh warga negara tanpa diskriminasi.",
      "Transformasi sektor energi menuju sumber terbarukan membutuhkan investasi besar, inovasi teknologi, serta komitmen politik yang kuat untuk mengurangi emisi karbon secara signifikan.",
      "Globalisasi ekonomi telah memperluas peluang perdagangan internasional, namun juga meningkatkan kerentanan terhadap fluktuasi pasar global dan ketidakpastian ekonomi dunia.",
      "Peningkatan kualitas sumber daya manusia melalui pendidikan dan pelatihan vokasional menjadi strategi utama dalam menghadapi tantangan revolusi industri modern.",
      "Pengelolaan kota berkelanjutan memerlukan perencanaan tata ruang yang terintegrasi dengan mempertimbangkan aspek lingkungan, sosial, dan ekonomi secara seimbang.",
      "Perkembangan ekonomi berbasis pengetahuan menempatkan inovasi, riset, dan penguasaan teknologi sebagai faktor utama dalam menentukan daya saing suatu negara.",
      "Kesadaran kolektif masyarakat terhadap pentingnya pelestarian lingkungan menjadi kunci dalam mengatasi berbagai permasalahan ekologis yang semakin kompleks.",
      "Pemanfaatan big data dalam pengambilan keputusan strategis memungkinkan analisis yang lebih akurat, namun juga memerlukan pengelolaan data yang bertanggung jawab dan etis.",
      "Reformasi birokrasi yang berkelanjutan bertujuan untuk menciptakan sistem pemerintahan yang lebih transparan, efisien, dan responsif terhadap kebutuhan masyarakat.",
      "Pengembangan sektor ekonomi kreatif berbasis budaya lokal dapat menjadi motor penggerak pertumbuhan ekonomi sekaligus menjaga identitas nasional.",
      "Ketimpangan sosial dan ekonomi yang masih terjadi di berbagai daerah memerlukan kebijakan afirmatif yang tepat sasaran untuk menciptakan pemerataan kesejahteraan.",
      "Kolaborasi antara sektor akademik, industri, dan pemerintah menjadi faktor kunci dalam mendorong inovasi dan percepatan pembangunan nasional.",
      "Perubahan iklim global menuntut adanya kebijakan adaptasi dan mitigasi yang komprehensif untuk melindungi ekosistem dan keberlanjutan kehidupan manusia.",
      "Digitalisasi sistem keuangan membuka akses yang lebih luas terhadap layanan perbankan, namun juga meningkatkan risiko keamanan siber yang perlu diantisipasi.",
      "Peningkatan literasi masyarakat terhadap teknologi informasi sangat penting untuk mencegah penyebaran informasi yang salah dan meningkatkan kualitas demokrasi.",
      "Pendekatan berbasis komunitas dalam pembangunan sosial terbukti efektif dalam meningkatkan partisipasi masyarakat dan keberhasilan program jangka panjang."
    ]
  },
  su: {
    easy: [
      "Ucing eta diuk dina samak bari nempo manuk di luar jandela kalawan tenang.",
      "Abdi resep tuang sangu goreng sareng nginum cai enteh unggal enjing sateuacan angkat.",
      "Panonpoe caang pisan sareng langit warnana biru dina enjing ieu anu sae pisan.",
      "Indung angkat ka pasar kanggo meser sayuran seger sareng bubuahan kanggo tuang wengi.",
      "Barudak arulin di taman kalawan bungah bari lumpat sareng seuri bareng babaturan.",
      "Bapa maos koran unggal enjing bari nginum kopi hideung di tepas bumi.",
      "Sakola urang gaduh perpustakaan anu ageung kalawan seueur buku carita anu pikaresepeun.",
      "Hujan turun kalawan deres dugi ka urang teu tiasa ulin di luar bumi dinten ieu.",
      "Nini masak rendang anu ngeunah pisan kanggo acara tuang bareng kulawarga ageung.",
      "Adi abdi diajar maca sareng nulis di sakola dasar kalawan rajin unggal dinten.",
      "Urang angkat ka basisir sareng ulin keusik bari ngaraos angin laut anu tiis.",
      "Tangkal buah di buruan bumi parantos buahan seueur sareng siap kanggo dipetik.",
      "Guru ngajarkeun urang cara ngitung sareng maca kalawan sabar di jero kelas.",
      "Lanceuk meser es krim rasa cokelat sareng vanila kanggo urang sadayana di sonten.",
      "Manuk-manuk disada merdu di enjing ngajadikeun kaayaan jadi pikabungaheun pisan.",
      "Abdi hudang isuk-isuk teras ngabantosan indung beberesih buruan bumi.",
      "Adi keur ulin sareng cocooan anyar anu dipasihkeun ku kolotna kamari.",
      "Urang diajar bareng di ruang tamu bari ngadengekeun musik anu leuleus.",
      "Bapa ngabenerkeun sapédah anu ruksak supados tiasa dipaké deui énjing.",
      "Indung masak sayur sop haneut anu ngeunah nalika cuaca keur tiis.",
      "Babaturan abdi sumping ka bumi kanggo ulin sareng ngerjakeun tugas babarengan.",
      "Urang nonton tipi bareng kulawarga saatos tuang wengi unggal dinten.",
      "Ucing piaraan urang sare nyenyak di luhur sofa ruang kulawarga.",
      "Abdi mawa bekel ti bumi kanggo didahar nalika waktos reureuh di sakola.",
      "Urang leumpang ka taman bari ngaraos hawa seger di sonten poé.",
      "Adi ngagambar imah sareng tangkal nganggo pensil warna dina buku gambarna.",
      "Indung ngumbah baju isuk-isuk teras ngeringkeun di buruan tukang.",
      "Bapa ngajak urang jalan-jalan ka kebon binatang nalika poé libur.",
      "Urang mésér buah seger di pasar kanggo didahar bareng kulawarga.",
      "Manuk leutik nincak dina dahan tangkal bari nyanyi sora anu éndah.",
      "Abdi maca buku carita sateuacan sare supados tiasa ngimpi anu saé.",
      "Urang ulin bal di lapang deukeut bumi bareng babaturan unggal sonten.",
      "Indung nyieun kue amis anu seungit sareng ngeunah kanggo urang sadayana.",
      "Adi diajar ngabeungkeut tali sapatu kalayan bantosan lanceukna.",
      "Urang ngabantosan kolot beberesih bumi supados tetep rapih sareng merenah."
    ],
    medium: [
      "Tatar Sunda kawentar ku kaendahan alamna anu asri sareng budayana anu kacida beungharna ti jaman baheula dugi ka ayeuna.",
      "Basa Sunda mangrupikeun salah sahiji basa daerah anu panglobana digunakeun di Indonesia sareng kedah dilestarikan ku urang sadayana.",
      "Kasenian Sunda sapertos jaipong, angklung, sareng wayang golek mangrupikeun warisan budaya anu teu ternilai hargana pikeun bangsa.",
      "Gunung Tangkuban Parahu mangrupikeun salah sahiji tempat wisata anu kawentar di Jawa Barat kalawan legenda Sangkuriang anu mashur.",
      "Kadaharan Sunda sapertos nasi timbel, lalapan, sareng sambal dadak dipikanyaho ku sadaya jalmi di sakuliah Nusantara.",
      "Pendidikan basa Sunda di sakola-sakola kedah ditingkatkeun supados generasi ngora tetep tiasa ngagunakeun basa indungna kalawan lancar.",
      "Seni tari Sunda ngagaduhan gerakan anu lemes sareng anggun anu ngagambarkeun kahalusan budi sareng kaendahan jiwa urang Sunda.",
      "Kawasan Bandung Utara mangrupikeun daerah konservasi anu kedah dijaga kalestarian alamna pikeun kasaean generasi anu bakal datang.",
      "Tradisi upacara adat Sunda sapertos Seren Taun masih dilaksanakeun ku masarakat pikeun ngarasa sukur kana hasil tatanen.",
      "Sastra Sunda ngagaduhan karya-karya anu luhung sapertos Lutung Kasarung, Ciung Wanara, sareng seueur deui anu pikaresepeun.",
      "Pamarentah daerah ngaupayakeun pelestarian budaya Sunda ngaliwatan rupa-rupa program pendidikan sareng festival budaya unggal taun.",
      "Industri kreatif di Tatar Sunda terus mekar kalawan ngamangpaatkeun teknologi modern pikeun ngamajukeun produk-produk lokal.",
      "Pariwisata di Jawa Barat terus dimekarkeun pikeun narik wisatawan lokal sareng mancanagara kalawan nawiskeun rupa-rupa pangalaman anu unik.",
      "Masarakat Sunda dipikawanoh ku sipat someah, ramah, sareng resep gotong royong dina kahirupan sapopoe.",
      "Pelestarian lingkungan di wewengkon pagunungan penting pisan pikeun ngajaga kasaimbangan ékosistem sareng sumber cai.",
      "Budaya ngariksa leuweung geus jadi bagian tina kahirupan masarakat adat Sunda ti jaman karuhun nepi ka ayeuna.",
      "Pangwangunan infrastruktur di wewengkon désa dipiharep tiasa ningkatkeun kahirupan ékonomi masarakat satempat.",
      "Pamakéan basa Sunda dina kahirupan sapopoe tiasa ngabantu ngajaga jati diri budaya di tengah arus globalisasi.",
      "Kagiatan seni budaya di sakola tiasa ngadorong murid pikeun leuwih mikaresep sareng ngariksa warisan karuhun.",
      "Pertanian di Tatar Sunda masih janten sumber panghasilan utama pikeun sabagian ageung masarakat désa.",
      "Perkembangan kota Bandung jadi pusat pendidikan sareng kreativitas anu narik loba nonoman pikeun diajar sareng berkarya.",
      "Pelatihan kaahlian pikeun nonoman penting pikeun nyiapkeun aranjeunna dina nyanghareupan dunya kerja anu beuki kompetitif.",
      "Kagiatan sosial di lingkungan kampung tiasa nguatkeun hubungan antar warga sareng ningkatkeun rasa silih asih.",
      "Pamarentah terus ngadorong digitalisasi pikeun ningkatkeun pelayanan publik anu langkung gancang sareng éfisién.",
      "Kagiatan maca buku tiasa ningkatkeun pangaweruh sareng kamampuhan mikir kritis pikeun sakumna umur.",
      "Pengelolaan sampah anu hadé tiasa ngajaga kabersihan lingkungan sareng kaséhatan masarakat.",
      "Kagiatan olahraga rutin tiasa ngajaga awak tetep séhat sareng pikiran janten leuwih seger.",
      "Peran kulawarga penting pisan dina ngadidik barudak supaya miboga akhlak anu hadé sareng tanggung jawab.",
      "Festival budaya Sunda jadi sarana pikeun ngenalkeun kasenian tradisional ka generasi ngora.",
      "Kerja bareng antara pamarentah sareng masarakat penting pikeun ngahontal kamajuan daérah.",
      "Pamakéan teknologi dina widang pendidikan tiasa ningkatkeun kualitas diajar ngajar sacara signifikan.",
      "Kamekaran usaha leutik di kampung tiasa ngabantu ningkatkeun ékonomi lokal sacara bertahap."
    ],
    hard: [
      "Transformasi sosial-budaya anu lumangsung di masarakat Sunda kontemporer mangrupikeun fenomena kompleks anu ngalibatkeun interaksi antawis nilai-nilai tradisional anu diwariskeun sacara turun-tumurun kalawan pangaruh modernisasi sareng globalisasi anu teu tiasa dihindarkeun.",
      "Pelestarian basa sareng budaya Sunda dina era digital merlukeun strategi komprehensif anu ngaintegrasikeun pendekatan konvensional kalawan inovasi teknologi pikeun mastikeun transmisi antargenerasi anu efektif sareng berkelanjutan.",
      "Kearifan lokal masarakat Sunda dina ngolah sumber daya alam sacara berkelanjutan ngandung prinsip-prinsip ekologis anu relevan kalawan konsep pembangunan berkelanjutan modern anu diakui sacara internasional.",
      "Perkembangan urbanisasi anu pesat di wilayah Tatar Sunda mawa tantangan signifikan dina ngajaga kasaimbangan antawis kamajuan ekonomi, pelestarian lingkungan hirup, sareng pemertahanan identitas budaya lokal.",
      "Kontribusi intelektual para cendekiawan Sunda dina khazanah ilmu pengetahuan nasional sareng internasional mangrupikeun bukti nyata tina potensi sumber daya manusia anu unggul di Tatar Sunda.",
      "Revitalisasi seni pertunjukan tradisional Sunda merlukeun pendekatan inovatif anu tiasa narik minat generasi ngora tanpa ngaleungitkeun esensi filosofis sareng estetis anu jadi ciri khasna.",
      "Pengembangan ekonomi kreatif berbasis budaya Sunda gaduh potensi anu ageung pikeun ningkatkeun kasejahteraan masarakat lokal bari sakaligus ngalestarikan warisan budaya anu teu ternilai hargana.",
      "Dinamika globalisasi anu terus ngembang nyiptakeun tekanan anyar kana eksistensi basa daerah, kalebet basa Sunda, anu merlukeun intervensi strategis dina widang pendidikan sareng kabijakan budaya.",
      "Integrasi teknologi digital dina sistem pendidikan Sunda tiasa janten katalis penting pikeun ningkatkeun aksés sareng kualitas pembelajaran di sagala lapisan masarakat.",
      "Pendekatan interdisipliner dina panalungtikan budaya Sunda ngamungkinkeun pamahaman anu langkung jero ngeunaan hubungan antara sajarah, basa, sareng struktur sosial masarakat.",
      "Penguatan identitas budaya lokal dina era modern janten penting pikeun nyegah erosi nilai-nilai tradisional anu tiasa leungit akibat pangaruh budaya global.",
      "Kebijakan pelestarian lingkungan di Tatar Sunda kedah ngagabungkeun élmu modéren sareng kearifan lokal pikeun ngahasilkeun solusi anu lestari sareng kontekstual.",
      "Peran lembaga pendidikan luhur di Jawa Barat penting pisan dina ngamekarkeun panalungtikan sareng inovasi anu nyoko kana budaya lokal.",
      "Transformasi digital dina sektor ekonomi lokal tiasa ngaronjatkeun daya saing produk-produk budaya Sunda di pasar global.",
      "Analisis sosiologis ngeunaan parobahan gaya hirup masarakat Sunda nunjukkeun ayana pergeseran nilai anu signifikan dina generasi ngora.",
      "Pengembangan pariwisata berbasis budaya kedah dilakukeun sacara bijaksana pikeun ngajaga kasaimbangan antara eksploitasi ekonomi sareng pelestarian budaya.",
      "Kolaborasi antara pamarentah, akademisi, sareng praktisi budaya penting pisan pikeun mastikeun kelestarian warisan budaya Sunda.",
      "Perubahan iklim global ogé mangaruhan pola kahirupan masarakat agraris di Tatar Sunda anu gumantung kana siklus alam.",
      "Inovasi dina widang seni rupa sareng desain tiasa janten sarana pikeun ngenalkeun budaya Sunda ka pasar internasional.",
      "Penguatan literasi digital di kalangan nonoman Sunda tiasa ngabantu dina nyaring informasi sareng nyegah disinformasi.",
      "Kajian linguistik ngeunaan basa Sunda nyumbang kana pamahaman anu langkung lega ngeunaan keragaman basa di Indonesia.",
      "Strategi pembangunan daerah berbasis budaya tiasa janten alternatif pikeun ngahontal pertumbuhan ekonomi anu inklusif.",
      "Pangaruh media sosial kana pola komunikasi masarakat Sunda nyiptakeun dinamika anyar dina panggunaan basa sapopoe.",
      "Pengelolaan sumber daya budaya sacara profesional tiasa ningkatkeun nilai ekonomi tanpa ngorbankeun integritas budaya.",
      "Pendekatan partisipatif dina pelestarian budaya ngamungkinkeun masarakat lokal pikeun aktip aub dina ngajaga warisan karuhun.",
      "Eksplorasi nilai-nilai filosofis dina budaya Sunda tiasa nyumbang kana diskursus global ngeunaan etika sareng kahirupan berkelanjutan."
    ]
  },
  jv: {
    easy: [
      "Kucing kuwi lungguh ing klasa lan ndeleng manuk ing njaba cendhela kanthi tentrem.",
      "Aku seneng mangan sega goreng lan ngombe teh manis saben esuk sadurunge mangkat.",
      "Srengenge padhang banget lan langite biru ing wayah esuk iki sing apik banget.",
      "Ibu lunga menyang pasar kanggo tuku sayuran seger lan woh-wohan kanggo mangan bengi.",
      "Bocah-bocah padha dolanan ing taman kanthi seneng karo mlayu lan ngguyu bareng kanca.",
      "Bapak maca koran saben esuk karo ngombe kopi ireng ing teras omah.",
      "Sekolah kita duwe perpustakaan gedhe kanthi akeh buku crita sing menarik kanggo diwaca.",
      "Udan deres banget nganti awake dhewe ora bisa dolanan ing njaba omah dina iki.",
      "Simbah masak rendang sing enak banget kanggo acara mangan bareng kulawarga gedhe.",
      "Adhiku sinau maca lan nulis ing sekolah dasar kanthi sregep saben dina.",
      "Awake dhewe lunga menyang pantai lan dolanan wedhi karo ngrasakake angin segara sing adhem.",
      "Wit pelem ing latar omah wis wohe akeh lan siap kanggo dipethik.",
      "Guru ngajari awake dhewe cara ngetung lan maca kanthi sabar ing jero kelas.",
      "Kakang tuku es krim rasa cokelat lan vanila kanggo awake dhewe kabeh ing sore.",
      "Manuk-manuk nyanyi merdu ing wayah esuk gawe swasana dadi nyenengake banget.",
      "Aku tangi esuk banjur mbantu ibu nyapu latar omah sadurunge sarapan.",
      "Adhiku dolanan karo dolanan anyar sing dituku wingi ing toko cedhak omah.",
      "Awake dhewe sinau bareng ing ruang tamu karo ngrungokake musik sing alus.",
      "Bapak ndandani sepeda sing rusak supaya bisa dienggo maneh sesuk esuk.",
      "Ibu masak sayur sop anget sing enak nalika cuaca lagi adhem.",
      "Kancaku teka menyang omah kanggo dolanan lan ngerjakake tugas bareng.",
      "Awake dhewe nonton televisi bareng kulawarga sawise mangan bengi saben dina.",
      "Kucing piaraan turu kepenak ing ndhuwur sofa ruang kulawarga.",
      "Aku nggawa bekal saka omah kanggo dipangan nalika wektu istirahat ing sekolah.",
      "Awake dhewe mlaku-mlaku menyang taman karo ngrasakake hawa seger ing sore dina.",
      "Adhiku nggambar omah lan wit nganggo pensil warna ing buku gambare.",
      "Ibu ngumbah klambi esuk-esuk banjur ngeringake ing latar mburi omah.",
      "Bapak ngajak awake dhewe dolan menyang kebon binatang nalika dina prei.",
      "Awake dhewe tuku woh-wohan seger ing pasar kanggo dipangan bareng kulawarga.",
      "Manuk cilik lungguh ing dahan wit karo nyanyi swara sing apik banget.",
      "Aku maca buku crita sadurunge turu supaya bisa ngimpi sing apik.",
      "Awake dhewe dolanan bal ing lapangan cedhak omah bareng kanca-kanca saben sore.",
      "Ibu nggawe kue manis sing wangi lan enak kanggo dipangan bareng.",
      "Adhiku sinau ngiket tali sepatu karo pitulungan saka kakang.",
      "Awake dhewe mbantu wong tuwa resik-resik omah supaya tetep rapi lan nyaman."
    ],
    medium: [
      "Tanah Jawa kondhang amarga kabudayane sing sugih lan alam sing endah wiwit jaman biyen nganti saiki tetep dilestarekake.",
      "Basa Jawa minangka salah sawijining basa daerah sing paling akeh digunakake ing Indonesia lan kudu dilestarekake dening kita kabeh.",
      "Kesenian Jawa kayata wayang kulit, gamelan, lan batik minangka warisan budaya sing ora bisa diukur regane kanggo bangsa.",
      "Candi Borobudur minangka salah sawijining warisan budaya donya sing dadi kebanggaan bangsa Indonesia lan narik wisatawan saka mancanegara.",
      "Panganan Jawa kayata gudeg, rawon, lan soto minangka kuliner sing wis kondhang ing saindhenging Nusantara lan mancanegara.",
      "Pendhidhikan basa Jawa ing sekolah-sekolah kudu ditingkatake supaya generasi mudha tetep bisa nggunakake basa ibune kanthi lancar.",
      "Seni tari Jawa nduweni gerakan sing alus lan anggun sing nggambarake kahalusan budi lan kaendahan jiwa wong Jawa.",
      "Falsafah urip wong Jawa sing ngutamakake keselarasan karo alam lan sesama manungsa isih relevan ing jaman modern iki.",
      "Tradisi upacara adat Jawa kayata Sekaten isih dileksanakake dening masyarakat kanggo nguri-uri warisan budaya leluhur.",
      "Sastra Jawa nduweni karya-karya sing adhiluhung kayata Serat Centhini, Serat Wedhatama, lan akeh maneh sing migunani.",
      "Pemerintah daerah ngupayakake pelestarian budaya Jawa liwat maneka program pendhidhikan lan festival budaya saben taun.",
      "Industri kreatif ing Tanah Jawa terus berkembang kanthi nggunakake teknologi modern kanggo majokake produk-produk lokal.",
      "Pariwisata ing Jawa terus dikembangake kanggo narik wisatawan lokal lan manca negara kanthi nyedhiyakake pengalaman sing unik lan menarik.",
      "Masyarakat Jawa dikenal kanthi sipat andhap asor, ramah, lan ngajeni marang wong liya ing saben interaksi sosial.",
      "Pelestarian lingkungan ing wilayah pegunungan penting banget kanggo njaga keseimbangan ekosistem lan sumber banyu.",
      "Budaya gotong royong ing desa-desa Jawa isih dijaga kanthi becik minangka wujud solidaritas antar warga.",
      "Pembangunan infrastruktur ing wilayah pedesaan diarepake bisa ningkatake kesejahteraan ekonomi masyarakat setempat.",
      "Panggunaan basa Jawa ing saben dinane bisa mbantu njaga identitas budaya ing tengah arus globalisasi.",
      "Kegiatan seni budaya ing sekolah bisa nyengkuyung siswa supaya luwih tresna marang warisan leluhur.",
      "Pertanian ing Tanah Jawa isih dadi sumber panguripan utama kanggo akeh masyarakat pedesaan.",
      "Perkembangan kutha-kutha gedhe ing Jawa mbutuhake perencanaan tata ruang sing apik supaya ora nimbulake masalah sosial.",
      "Pelatihan keterampilan kanggo para mudha penting kanggo nyiapake dheweke ing donya kerja sing saya kompetitif.",
      "Kegiatan sosial ing lingkungan masyarakat bisa nguatake hubungan antar warga lan nambah rasa kebersamaan.",
      "Pemerintah terus nyengkuyung digitalisasi kanggo ningkatake pelayanan publik sing luwih cepet lan efisien.",
      "Kebiasaan maca buku kanthi rutin bisa nambah wawasan lan kemampuan mikir kritis.",
      "Pengelolaan sampah sing becik bisa njaga kebersihan lingkungan lan kesehatan masyarakat.",
      "Olahraga kanthi teratur bisa njaga awak tetep sehat lan pikiran luwih seger.",
      "Peran kulawarga penting banget kanggo mbentuk karakter lan kepribadian anak wiwit cilik.",
      "Festival budaya Jawa dadi sarana kanggo ngenalake kesenian tradisional marang generasi enom.",
      "Kerja sama antar lembaga lan masyarakat penting kanggo nggayuh pembangunan daerah sing berkelanjutan.",
      "Pemanfaatan teknologi ing bidang pendidikan bisa ningkatake kualitas proses sinau lan ngajar.",
      "Pengembangan usaha cilik lan menengah bisa ndhukung pertumbuhan ekonomi lokal kanthi bertahap."
    ],
    hard: [
      "Transformasi sosial-budaya sing dumadi ing masyarakat Jawa kontemporer minangka fenomena kompleks sing nglibatake interaksi antarane nilai-nilai tradisional sing diwarisake kanthi turun-temurun karo pengaruh modernisasi lan globalisasi sing ora bisa dihindarake.",
      "Pelestarian basa lan budaya Jawa ing era digital mbutuhake strategi komprehensif sing ngintegrasikake pendekatan konvensional karo inovasi teknologi kanggo njamin transmisi antargenerasi sing efektif lan berkelanjutan.",
      "Kearifan lokal masyarakat Jawa ing ngolah sumber daya alam kanthi berkelanjutan ngandhut prinsip-prinsip ekologis sing relevan karo konsep pembangunan berkelanjutan modern sing diakoni sacara internasional.",
      "Perkembangan urbanisasi sing cepet ing wilayah Tanah Jawa nggawa tantangan signifikan ing njaga keseimbangan antarane kemajuan ekonomi, pelestarian lingkungan urip, lan pemertahanan identitas budaya lokal.",
      "Kontribusi intelektual para cendekiawan Jawa ing khazanah ilmu pengetahuan nasional lan internasional minangka bukti nyata saka potensi sumber daya manusia sing unggul ing Tanah Jawa.",
      "Revitalisasi seni pertunjukan tradisional Jawa mbutuhake pendekatan inovatif sing bisa narik minat generasi mudha tanpa ngilangake esensi filosofis lan estetis sing dadi ciri khase.",
      "Pengembangan ekonomi kreatif berbasis budaya Jawa nduweni potensi sing gedhe kanggo ningkatake kesejahteraan masyarakat lokal karo bebarengan ngelestarekake warisan budaya sing ora ternilai regane.",
      "Dinamika globalisasi sing terus berkembang menehi tekanan anyar marang eksistensi basa daerah, kalebu basa Jawa, sing mbutuhake kebijakan strategis ing bidang pendidikan lan kebudayaan.",
      "Integrasi teknologi digital ing sistem pendidikan Jawa bisa dadi faktor penting kanggo ningkatake akses lan kualitas pembelajaran ing macem-macem lapisan masyarakat.",
      "Pendekatan interdisipliner ing panaliten budaya Jawa menehi kesempatan kanggo mangerteni hubungan kompleks antarane sejarah, basa, lan struktur sosial masyarakat.",
      "Penguatan identitas budaya lokal ing jaman modern dadi penting kanggo nyegah pudhake nilai-nilai tradisional amarga pengaruh budaya global.",
      "Kebijakan pelestarian lingkungan ing Tanah Jawa kudu nggabungake ilmu modern lan kearifan lokal supaya bisa ngasilake solusi sing lestari lan kontekstual.",
      "Peran perguruan tinggi ing Jawa penting banget kanggo ngembangake riset lan inovasi sing adhedhasar budaya lokal.",
      "Transformasi digital ing sektor ekonomi lokal bisa ningkatake daya saing produk budaya Jawa ing pasar global.",
      "Analisis sosiologis babagan owah-owahan gaya urip masyarakat Jawa nuduhake ana pergeseran nilai sing cukup signifikan ing kalangan generasi enom.",
      "Pengembangan pariwisata berbasis budaya kudu ditindakake kanthi bijaksana supaya njaga keseimbangan antarane kepentingan ekonomi lan pelestarian budaya.",
      "Kolaborasi antarane pemerintah, akademisi, lan pelaku budaya dadi faktor penting kanggo njaga kelestarian warisan budaya Jawa.",
      "Perubahan iklim global uga nduweni pengaruh marang pola urip masyarakat agraris ing Tanah Jawa sing gumantung marang siklus alam.",
      "Inovasi ing bidang seni lan desain bisa dadi sarana kanggo ngenalake budaya Jawa marang masyarakat internasional.",
      "Penguatan literasi digital ing kalangan generasi enom Jawa bisa mbantu nyaring informasi lan nyegah panyebaran kabar sing ora bener.",
      "Kajian linguistik babagan basa Jawa menehi kontribusi penting kanggo mangerteni keragaman basa ing Indonesia.",
      "Strategi pembangunan daerah berbasis budaya bisa dadi alternatif kanggo nggayuh pertumbuhan ekonomi sing inklusif lan berkelanjutan.",
      "Pengaruh media sosial marang pola komunikasi masyarakat Jawa nyiptakake dinamika anyar ing panggunaan basa saben dinane.",
      "Pengelolaan sumber daya budaya kanthi profesional bisa ningkatake nilai ekonomi tanpa ngorbanake keaslian budaya.",
      "Pendekatan partisipatif ing pelestarian budaya menehi kesempatan marang masyarakat lokal kanggo aktif melu njaga warisan leluhur.",
      "Eksplorasi nilai-nilai filosofis ing budaya Jawa bisa menehi kontribusi marang diskursus global babagan etika lan pembangunan berkelanjutan."
    ]
  }
};

export function getRandomSentences(lang, difficulty, count) {
  lang = lang || 'en';
  difficulty = difficulty || 'medium';
  count = count || 3;
  var pool = (sentences[lang] && sentences[lang][difficulty]) ? sentences[lang][difficulty] : sentences.en.medium;
  var shuffled = pool.slice().sort(function() { return Math.random() - 0.5; });
  var selected = shuffled.slice(0, Math.min(count, shuffled.length));
  return selected.join(' ');
}

export function getLanguages() {
  return [
    { code: 'en', name: 'English', flag: '🇬🇧' },
    { code: 'id', name: 'Indonesia', flag: '🇮🇩' },
    { code: 'su', name: 'Sunda', flag: '🏔️' },
    { code: 'jv', name: 'Jawa', flag: '🏛️' }
  ];
}

export function getDifficulties() {
  return [
    { code: 'easy', name: 'Easy', icon: '🟢', desc: 'Simple words and short sentences' },
    { code: 'medium', name: 'Medium', icon: '🟡', desc: 'Standard sentences' },
    { code: 'hard', name: 'Hard', icon: '🔴', desc: 'Complex and long sentences' }
  ];
}
